version: '3.8'

x-rabbit-creds:
  environment:
    &rabbit-env
    RABBITMQ_USER: &rabbit-user rabbit
    RABBITMQ_PASS: &rabbit-pass password
    RABBITMQ_HOST: &rabbit-host rabbitmq
    RABBITMQ_PORT: &rabbit-port 5672

x-converter-conf:
  environnment:
    &converter-env
    CONVERTER_QUEUE: convert


services:
  docx-to-html:
    build: ./src
    command: gunicorn -w 4 -b 0.0.0.0:5000 -t 600 "app:create_app()"
    ports:
      - "5000:5000"
    volumes:
      - ./model_dir:/model_dir
      
  # sphinx-docs:
  #   build: ./src
  #   command: python -m http.server 7000 --directory docs/_build/html
  #   ports:
  #     - "7000:7000"

  web-api:
    build: ./src
    command: fastapi run api.py
    ports:
      - 8000:8000
    environment: 
      <<: [*rabbit-env, *converter-env]
    volumes:
      - ./model_dir:/model_dir
    depends_on:
      - rabbitmq

  docx-to-html-worker:
    build: ./src
    command: python3 worker.py
    restart: always
    environment: 
      <<: [*rabbit-env, *converter-env]
    volumes:
      - ./model_dir:/model_dir
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.10.7-management
    ports:
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: *rabbit-user
      RABBITMQ_DEFAULT_PASS: *rabbit-pass
    volumes:
      - ./model_dir:/model_dir
