version: '3.8'

x-rabbit-creds:
  environment:
    &rabbit-env
    RABBITMQ_USER: &rabbit-user rabbit
    RABBITMQ_PASS: &rabbit-pass password
    RABBITMQ_HOST: &rabbit-host rabbitmq
    RABBITMQ_PORT: &rabbit-port 5672

x-converter-conf:
  environnment:
    &converter-env
    CONVERTER_QUEUE: convert
    MAX_CONVERTER_FUTURES: 2
  uvicorn-max-concurrency: &max-concurrency '4'


services:
  docx-to-html:
    image: doc-parse:latest
    command: ['uvicorn', '--host', '0.0.0.0', '--port',  '5000', 'app:create_app']
    ports:
      - "5000:5000"
      
  # sphinx-docs:
  #   build: ./src
  #   command: python -m http.server 7000 --directory docs/_build/html
  #   ports:
  #     - "7000:7000"

  web-api:
    image: doc-parse:latest
    command: ['uvicorn', '--limit-concurrency', *max-concurrency, '--host', '0.0.0.0', '--port',  '8000', 'api:create_app']
    ports:
      - 8000:8000
    environment: 
      <<: [*rabbit-env, *converter-env]
    depends_on:
      - rabbitmq

  docx-to-json-worker:
    image: doc-parse:latest
    command: python3 worker.py
    restart: always
    environment: 
      <<: [*rabbit-env, *converter-env]
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.10.7-management
    ports:
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: *rabbit-user
      RABBITMQ_DEFAULT_PASS: *rabbit-pass
