version: '3.8'

x-rabbit-creds:
  environment:
    &rabbit-env
    RABBITMQ_USER: &rabbit-user rabbit
    RABBITMQ_PASS: &rabbit-pass password
    RABBITMQ_HOST: &rabbit-host rabbitmq
    RABBITMQ_PORT: &rabbit-port 5672

x-converter-conf:
  environnment:
    &converter-env
    CONVERTER_QUEUE: convert


services:
  docx-to-html:
    build: ./src
    ports:
      - "5000:5000"

  web-api:
    build: ./src
    command: fastapi run api.py
    ports:
      - 8000:8000
    environment: 
      <<: [*rabbit-env, *converter-env]
    depends_on:
      - rabbitmq

  docx-to-html-worker:
    build: ./src
    command: python3 worker.py
    restart: always
    environment: 
      <<: [*rabbit-env, *converter-env]
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.10.7-management
    ports:
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: *rabbit-user
      RABBITMQ_DEFAULT_PASS: *rabbit-pass

